[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000

; Modo dinámico: escala según la carga
pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests = 500

; Timeouts
request_terminate_timeout = 60s

; Logs de peticiones lentas (>3s)
slowlog = /proc/self/fd/2
request_slowlog_timeout = 3s
